import { useEffect, useState } from "react";
import { Mail, MapPin, Phone } from "lucide-react";
import MainLayout from "../components/layout/MainLayout";
import Container from "../components/ui/Container";
import Button from "../components/ui/Button";
import useScrollEffects from "../hooks/useScrollEffects";
import styles from "./contact/Contact.module.css";

function Heading({children}){return <div className={styles.heading}><h2>{children}</h2><span/></div>}
function Hero(){return <section className={styles.hero}><img src="/mandalay/mdy-camp.jpg" alt=""/><div><h1>Contact us</h1><span/></div></section>}
function ContactStrip(){return <section className={styles.strip}><Container narrow><div><Phone/><span><b>Admissions hotline</b><a href="tel:+959777603000">+95 (9) 777 60 3000</a></span></div><div><Mail/><span><b>Admissions email</b><a href="mailto:admissions.mdy@yismyanmar.com">admissions.mdy@yismyanmar.com</a></span></div><div><Mail/><span><b>Business office</b><a href="mailto:businessoffice@yismyanmar.com">businessoffice@yismyanmar.com</a></span></div></Container></section>}
function FindUs(){return <section className={styles.find}><Container narrow><Heading>Find us</Heading><div className={styles.findGrid}><article><h3>YIS Mandalay</h3><div><MapPin/><span><b>Address</b>No. 2/2, Between 62nd &amp; 63rd Street,<br/>Mahar Aung Myay Township, Mandalay</span></div><div><Mail/><span><b>General enquiries</b><a href="mailto:admissions.mdy@yismyanmar.com">admissions.mdy@yismyanmar.com</a></span></div><footer><b>Follow us</b><nav aria-label="Social media"><a href="https://www.facebook.com/YISMandalay" aria-label="Facebook">f</a><a href="https://www.instagram.com" aria-label="Instagram">◎</a><a href="https://www.youtube.com" aria-label="YouTube">▶</a></nav></footer></article><div className={styles.map}><iframe title="YIS Mandalay location on Google Maps" src="https://www.google.com/maps?q=No.%202%2F2%2C%20Between%2062nd%20%26%2063rd%20Street%2C%20Mahar%20Aung%20Myay%20Township%2C%20Mandalay%2C%20Myanmar&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></div></Container></section>}
function MessageForm(){const [draft,setDraft]=useState("");function submit(e){e.preventDefault();const v=new FormData(e.currentTarget);const body=`Campus: ${v.get("campus")}\nPhone: ${v.get("phone")}\n\n${v.get("message")}\n\nFrom: ${v.get("name")}\nEmail: ${v.get("email")}`;setDraft(`mailto:admissions.mdy@yismyanmar.com?subject=${encodeURIComponent(v.get("subject"))}&body=${encodeURIComponent(body)}`)}return <section className={styles.message}><Container narrow><div><small>Get in touch</small><h2>Send us a message</h2><i/><p>Whether you have a question about admissions, programmes, or school life at YIS, our team is happy to help. Fill in the form and we will be in touch as soon as possible.</p><aside><b>Office hours</b><strong>Monday – Friday</strong><span>7:30 AM – 4:30 PM</span><strong>Saturday – Sunday</strong><span>Closed</span></aside></div><form onSubmit={submit} onChange={()=>setDraft("")}><div className={styles.formGrid}><label>Full name *<input name="name" placeholder="Your full name" required/></label><label>Email address *<input name="email" type="email" placeholder="your@email.com" required/></label><label>Phone number<input name="phone" type="tel" placeholder="+95 9 ..."/></label><label>Campus<select name="campus"><option>Mandalay Campus</option><option>Yangon Campus</option></select></label><label className={styles.full}>Subject *<select name="subject" required defaultValue=""><option value="" disabled>Select a subject...</option><option>Admissions enquiry</option><option>Campus tour</option><option>Academic programmes</option><option>General enquiry</option></select></label><label className={styles.full}>Message *<textarea name="message" rows="6" placeholder="Write your message here..." required/></label></div><Button type="submit">Send message</Button>{draft&&<p className={styles.status} role="status">Your message is ready, but has not been sent. <a href={draft}>Open your email app to send it.</a></p>}</form></Container></section>}
export default function ContactPage(){useScrollEffects();useEffect(()=>{const p=document.title;document.title="Contact Us | Yangon International School";return()=>{document.title=p}},[]);return <MainLayout><Hero/><ContactStrip/><FindUs/><MessageForm/></MainLayout>}
