import { useEffect, useState } from "react";
import MainLayout from "../components/layout/MainLayout";
import Container from "../components/ui/Container";
import styles from "./welcome/WelcomeMessages.module.css";
import useScrollEffects from "../hooks/useScrollEffects";

const leaders = [
  { id:"director", name:"School Director", role:"Director", email:"admissions.ygn@yis-yangon.edu.mm", image:"about-yis.webp", greeting:"Dear YIS Families, Students, and Visitors,", paragraphs:["Welcome to Yangon International School. For over two decades, YIS has had the privilege of serving local and international families across Myanmar, and it remains an honour to be part of a community as vibrant and dedicated as ours.","At YIS, we are guided by a belief that education is most powerful when it is both rigorous and human. Our American-based curriculum, complemented by the International Baccalaureate Diploma Programme, is designed not only to prepare students for the world's top universities, but to shape them into lifelong learners and global citizens who are equipped to navigate — and lead in — an interconnected world.","Central to our philosophy is the partnership between family and school. Students thrive when the adults in their lives — parents and educators alike — work together with shared purpose and open communication. We welcome your engagement, your questions, and your ideas.","We are proud of the legacy that YIS has built and even more excited by what lies ahead. Thank you for being part of our story."]},
  { id:"principal", name:"School Principal", role:"Principal", email:"admissions.ygn@yis-yangon.edu.mm", image:"about-yis-2.webp", greeting:"Dear Students, Families, and Friends,", paragraphs:["It is my pleasure to welcome you to YIS, a school where every student is known, supported, and challenged to reach their full potential.","Learning here is active, purposeful, and deeply connected to the world beyond our classrooms. Our teachers create environments where curiosity is encouraged, ideas are respected, and students grow in confidence through meaningful academic and personal experiences.","We believe strong schools are built on strong relationships. The partnership between our educators and families enables us to care for the whole child while maintaining high expectations for learning, character, and citizenship.","Thank you for choosing to learn more about our community. We look forward to welcoming you to campus."]},
  { id:"activities", name:"Activities Leadership", role:"Athletics & Activities Director", email:"admissions.ygn@yis-yangon.edu.mm", image:"art.jpg", greeting:"Dear YIS Community,", paragraphs:["Student life at YIS extends well beyond the school day. Athletics, the arts, clubs, service, and leadership opportunities give students the space to discover new interests and build lasting friendships.","Our activities programme is designed for participation, growth, and belonging. Whether students are performing, competing, creating, or serving, they develop teamwork, resilience, responsibility, and pride in representing their school.","We encourage every student to take part, try something new, and contribute their talents to our community.","We look forward to seeing you at an upcoming game, performance, exhibition, or community event."]},
];

function Hero(){return <section className={styles.hero}><img src="/mandalay/23-scaled.jpg" alt=""/><div><h1>Welcome messages</h1><span/></div></section>}

export default function WelcomeMessagesPage(){
  useScrollEffects();
  const [selected,setSelected]=useState(leaders[0]);
  useEffect(()=>{const previous=document.title;document.title="Welcome Messages | Yangon International School";return()=>{document.title=previous}},[]);
  return <MainLayout><Hero/><section className={styles.messages}><Container narrow><div className={styles.layout}>
    <aside><h2>Leadership team</h2>{leaders.map(leader=><button key={leader.id} className={selected.id===leader.id?styles.active:""} onClick={()=>setSelected(leader)}><img src={`/mandalay/${leader.image}`} alt=""/><span><strong>{leader.name}</strong><small>{leader.role}</small></span></button>)}<div className={styles.contact}><b>Contact</b><a href={`mailto:${selected.email}`}>{selected.email}</a></div></aside>
    <div><article className={styles.letter}><header><img src={`/mandalay/${selected.image}`} alt=""/><div><h2>{selected.name}</h2><strong>{selected.role}</strong><span>Yangon International School</span></div></header><div className={styles.body}><span className={styles.quote}>”</span><p><em>{selected.greeting}</em></p>{selected.paragraphs.map(text=><p key={text}>{text}</p>)}<footer><em>Warm regards,</em><strong>{selected.name}</strong><b>{selected.role}</b><a href={`mailto:${selected.email}`}>{selected.email}</a></footer></div></article><nav className={styles.tabs} aria-label="Welcome messages">{leaders.map(leader=><button key={leader.id} className={selected.id===leader.id?styles.active:""} onClick={()=>setSelected(leader)}>{leader.role}</button>)}</nav></div>
  </div></Container></section></MainLayout>;
}
